<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK6XNhGr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK6XNhGr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK6XNhGr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK6XNhGr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK6XNhGr\App_KernelDevDebugContainer([
    'container.build_hash' => 'K6XNhGr',
    'container.build_id' => '8fb91393',
    'container.build_time' => 1706198625,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK6XNhGr');
