<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNoi6Akg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNoi6Akg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNoi6Akg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNoi6Akg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNoi6Akg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Noi6Akg',
    'container.build_id' => '5a8a7a79',
    'container.build_time' => 1706535062,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNoi6Akg');
